<?php
declare(strict_types=1);

function sponsor_admin_escape($value): string { return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function sponsor_admin_date(string $value): string {
    return (new DateTimeImmutable($value, new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Europe/Amsterdam'))->format('d-m-Y H:i');
}
function sponsor_admin_money($value): string { return '€ ' . number_format((float)$value, 0, ',', '.'); }
function sponsor_admin_mail_label(?string $state): string {
    return ['sent' => 'Verstuurd', 'pending' => 'Wacht op verzending', 'sending' => 'Controle nodig', 'uncertain' => 'Controle nodig'][$state ?? ''] ?? 'Onbekend';
}
function sponsor_admin_icon(string $name): string {
    return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><use href="/assets/icons.svg#' . sponsor_admin_escape($name) . '"></use></svg>';
}
function sponsor_admin_url(array $params): string { return '/beheer/?' . http_build_query($params); }
function sponsor_admin_header(string $title, string $csrf = ''): void {
    header('Content-Type: text/html; charset=utf-8');
    ?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#104a38"><title><?= sponsor_admin_escape($title) ?> · IJsbaan Neder-Betuwe</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/beheer/styles.css"><script src="/beheer/login.js" defer></script></head><body>
    <header class="admin-header"><a class="admin-brand" href="/beheer/"><?= sponsor_admin_icon('snowflake') ?><span>IJsbaan <strong>Neder-Betuwe</strong></span></a><div class="header-actions"><a href="/">Naar de website <?= sponsor_admin_icon('arrow-up-right') ?></a><?php if ($csrf): ?><form method="post" action="/beheer/"><input type="hidden" name="action" value="logout"><input type="hidden" name="csrf" value="<?= sponsor_admin_escape($csrf) ?>"><button type="submit">Uitloggen</button></form><?php endif; ?></div></header><main class="admin-main">
    <?php
}
function sponsor_admin_footer(): void {
    ?></main><footer class="admin-footer">IJsbaan Neder-Betuwe · Alleen voor de organisatie.</footer></body></html><?php
}
function sponsor_admin_login_page(): void {
    sponsor_admin_header('Inloggen sponsorbeheer'); ?>
    <section class="login-card"><span class="login-icon"><?= sponsor_admin_icon('users-round') ?></span><p class="eyebrow">VOOR DE WINTERMAKERS</p><h1>Sponsorbeheer</h1><p>Alle aanvragen op één plek. Dit overzicht is alleen toegankelijk voor de organisatie.</p><div class="login-instruction"><strong>Open Sponsorbeheer op je pc</strong><p>Dubbelklik op <b>Open sponsorbeheer.cmd</b> in je ijsbaanprojectmap. Je wordt automatisch ingelogd, zonder een wachtwoord over te typen.</p></div><p class="login-hint">Eenmaal ingelogd kun je deze pagina als bladwijzer bewaren. Als je opnieuw moet inloggen, gebruik je dezelfde opener op je pc.</p><p id="login-status" role="status" aria-live="polite"></p></section>
    <?php sponsor_admin_footer();
}
function sponsor_admin_mail_badge(?string $state): string {
    return '<span class="mail-badge ' . ($state === 'sent' ? 'mail-sent' : 'mail-pending') . '">' . sponsor_admin_icon($state === 'sent' ? 'check' : 'circle-question-mark') . sponsor_admin_escape(sponsor_admin_mail_label($state)) . '</span>';
}
function sponsor_admin_list(array $apps, array $filters, array $stats, array $counts, array $editions, array $packages, int $page, int $pages, string $csrf): void {
    sponsor_admin_header('Sponsoraanvragen', $csrf);
    $test = $filters['view'] === 'test';
    $currentEdition = sponsor_catalog()['edition'];
    $knownEditions = [$currentEdition['id'] => $currentEdition['place'] . ' ' . $currentEdition['season']];
    ?>
    <section class="overview-intro"><div><p class="eyebrow">SAMEN MAKEN WE DE WINTER MOGELIJK</p><h1>Sponsoraanvragen<span>.</span></h1><p>Bekijk wie er meedoet, welk pakket is aangevraagd en of de e-mails zijn verstuurd.</p></div><a class="button" href="<?= sponsor_admin_escape(sponsor_admin_url(array_merge($filters, ['csv' => 1]))) ?>"><?= sponsor_admin_icon('download') ?> Download CSV</a></section>
    <nav class="view-tabs" aria-label="Soort aanvragen"><a <?= !$test ? 'aria-current="page"' : '' ?> href="/beheer/">Sponsoraanvragen <span><?= (int)($counts[0] ?? 0) ?></span></a><a <?= $test ? 'aria-current="page"' : '' ?> href="/beheer/?view=test">Testaanvragen <span><?= (int)($counts[1] ?? 0) ?></span></a></nav>
    <?php if ($test): ?><p class="test-notice"><?= sponsor_admin_icon('circle-question-mark') ?> Je bekijkt technische tests. Deze tellen niet mee als echte sponsoraanvragen.</p><?php endif; ?>
    <div class="stats"><article><span>Bedrijven / organisaties</span><strong><?= (int)$stats['companies'] ?></strong></article><article><span><?= $test ? 'Testaanvragen' : 'Aanvragen' ?></span><strong><?= (int)$stats['total'] ?></strong></article><article><span><?= $test ? 'Bedrag in tests' : 'Aangevraagd totaal' ?></span><strong><?= sponsor_admin_money($stats['amount']) ?></strong><small>Dit is geen overzicht van betalingen.</small></article></div>
    <section class="overview-panel" aria-label="Overzicht van aanvragen"><form class="filters" method="get" action="/beheer/"><input type="hidden" name="view" value="<?= $test ? 'test' : 'real' ?>"><label class="search-label">Zoeken<input type="search" name="q" value="<?= sponsor_admin_escape($filters['q']) ?>" placeholder="Bedrijf, naam, e-mail of aanvraagnummer" maxlength="160"></label><label>Editie<select name="edition"><option value="">Alle edities</option><?php foreach ($editions as $edition): ?><option value="<?= sponsor_admin_escape($edition) ?>" <?= $filters['edition'] === $edition ? 'selected' : '' ?>><?= sponsor_admin_escape($knownEditions[$edition] ?? $edition) ?></option><?php endforeach; ?></select></label><label>Pakket<select name="package"><option value="">Alle pakketten</option><?php foreach ($packages as $amount): ?><option value="<?= (int)$amount ?>" <?= $filters['package'] === (string)$amount ? 'selected' : '' ?>><?= sponsor_admin_money($amount) ?></option><?php endforeach; ?></select></label><button class="button" type="submit">Toon resultaten</button><?php if ($filters['q'] || $filters['edition'] || $filters['package']): ?><a class="clear-filters" href="<?= $test ? '/beheer/?view=test' : '/beheer/' ?>">Wis filters</a><?php endif; ?></form>
    <?php if (!$apps): ?><div class="empty-state"><span><?= sponsor_admin_icon('ticket') ?></span><h2><?= $filters['q'] || $filters['edition'] || $filters['package'] ? 'Geen passende aanvragen.' : ($test ? 'Nog geen testaanvragen.' : 'De eerste wintermaker is welkom.') ?></h2><p><?= $filters['q'] || $filters['edition'] || $filters['package'] ? 'Pas de zoekopdracht of filters aan om andere aanvragen te bekijken.' : 'Zodra iemand een sponsorpakket aanvraagt, verschijnen de gegevens hier automatisch.' ?></p><?php if (!$test && !empty($counts[1])): ?><a href="/beheer/?view=test">Bekijk de technische testaanvraag <?= sponsor_admin_icon('arrow-up-right') ?></a><?php endif; ?></div>
    <?php else: ?><div class="table-wrap"><table class="applications-table"><caption class="sr-only"><?= $test ? 'Technische testaanvragen' : 'Ontvangen sponsoraanvragen' ?></caption><thead><tr><th scope="col">Bedrijf & contact</th><th scope="col">Pakket</th><th scope="col">Ontvangen</th><th scope="col">E-mails</th><th scope="col">Logo</th><th scope="col"><span class="sr-only">Details</span></th></tr></thead><tbody>
    <?php foreach ($apps as $app): $snapshot = json_decode($app['snapshot_json'], true); ?>
      <tr><td data-label="Bedrijf & contact"><a class="company-link" href="<?= sponsor_admin_escape(sponsor_admin_url(['id' => $app['reference']])) ?>"><?= sponsor_admin_escape($app['company']) ?></a><span class="contact-name"><?= sponsor_admin_escape($app['contact_name']) ?></span><a class="email-link" href="mailto:<?= sponsor_admin_escape($app['email']) ?>"><?= sponsor_admin_escape($app['email']) ?></a></td><td data-label="Pakket"><strong class="package-amount"><?= sponsor_admin_money($app['package_amount']) ?></strong><small><?= isset($snapshot['package']['coins']) ? (int)$snapshot['package']['coins'] . ' munten' : 'Hoofdsponsor' ?></small></td><td data-label="Ontvangen"><time><?= sponsor_admin_escape(sponsor_admin_date($app['created_at'])) ?></time><small><?= sponsor_admin_escape($app['reference']) ?></small></td><td data-label="E-mails"><span class="recipient-status"><small>Ton</small><?= sponsor_admin_mail_badge($app['organizer_state']) ?></span><span class="recipient-status"><small>Sponsor</small><?= sponsor_admin_mail_badge($app['sponsor_state']) ?></span></td><td data-label="Logo"><?php if ($app['logo_file']): ?><a class="logo-link" href="<?= sponsor_admin_escape(sponsor_admin_url(['logo' => $app['reference']])) ?>" aria-label="Download logo van <?= sponsor_admin_escape($app['company']) ?>"><?= sponsor_admin_icon('download') ?> Logo</a><?php else: ?><span class="muted">Niet toegevoegd</span><?php endif; ?></td><td><a class="details-link" href="<?= sponsor_admin_escape(sponsor_admin_url(['id' => $app['reference']])) ?>" aria-label="Bekijk aanvraag van <?= sponsor_admin_escape($app['company']) ?>">Bekijk <?= sponsor_admin_icon('arrow-up-right') ?></a></td></tr>
    <?php endforeach; ?></tbody></table></div><div class="pagination"><span><?= (int)$stats['total'] ?> <?= (int)$stats['total'] === 1 ? 'aanvraag' : 'aanvragen' ?> · pagina <?= $page ?> van <?= $pages ?></span><div><?php if ($page > 1): ?><a href="<?= sponsor_admin_escape(sponsor_admin_url(array_merge($filters, ['page' => $page - 1]))) ?>">Vorige</a><?php endif; ?><?php if ($page < $pages): ?><a href="<?= sponsor_admin_escape(sponsor_admin_url(array_merge($filters, ['page' => $page + 1]))) ?>">Volgende</a><?php endif; ?></div></div><?php endif; ?></section>
    <p class="overview-note">Een aanvraag is nog geen definitieve afspraak. ‘Verstuurd’ betekent dat de mailserver het bericht heeft aangenomen; het is geen leesbevestiging. De CSV bevat de resultaten van je huidige filters.</p>
    <?php sponsor_admin_footer();
}
function sponsor_admin_detail(array $app, string $csrf): void {
    sponsor_admin_header('Aanvraag ' . $app['reference'], $csrf);
    $snapshot = json_decode($app['snapshot_json'], true);
    ?>
    <a class="back-link" href="<?= $app['is_test'] ? '/beheer/?view=test' : '/beheer/' ?>">← Terug naar het overzicht</a><section class="detail-heading"><p class="eyebrow"><?= sponsor_admin_escape($app['reference']) ?></p><h1><?= sponsor_admin_escape($app['company']) ?></h1><p>Ontvangen op <?= sponsor_admin_escape(sponsor_admin_date($app['created_at'])) ?> · <?= sponsor_admin_escape($snapshot['edition']['place'] . ' ' . $snapshot['edition']['season']) ?></p></section>
    <?php if ($app['is_test']): ?><p class="test-notice"><?= sponsor_admin_icon('circle-question-mark') ?> Technische test. Niet verwerken of factureren als sponsoraanvraag.</p><?php endif; ?>
    <div class="detail-grid"><section class="detail-card"><h2>Contactgegevens</h2><dl><div><dt>Contactpersoon</dt><dd><?= sponsor_admin_escape($app['contact_name']) ?></dd></div><div><dt>E-mailadres</dt><dd><a href="mailto:<?= sponsor_admin_escape($app['email']) ?>"><?= sponsor_admin_escape($app['email']) ?></a></dd></div><div><dt>Telefoon</dt><dd><?= sponsor_admin_escape($app['phone'] ?: 'Niet ingevuld') ?></dd></div></dl><h3>Opmerkingen en wensen</h3><p class="notes"><?= sponsor_admin_escape($app['notes'] ?: 'Geen opmerkingen toegevoegd.') ?></p></section><section class="detail-card package-detail"><p class="eyebrow">AANGEVRAAGD PAKKET</p><h2><?= sponsor_admin_money($app['package_amount']) ?></h2><ul><?php foreach ($snapshot['package']['benefits'] as $benefit): ?><li><?= sponsor_admin_escape($benefit) ?></li><?php endforeach; ?></ul><p class="muted">Dit zijn de pakketgegevens zoals ze bij de aanvraag waren.</p></section><section class="detail-card"><h2>Logo</h2><?php if ($app['logo_file']): ?><p>Het logo is veilig opgeslagen. Je kunt het hieronder downloaden.</p><a class="button" href="<?= sponsor_admin_escape(sponsor_admin_url(['logo' => $app['reference']])) ?>"><?= sponsor_admin_icon('download') ?> Download logo</a><?php else: ?><p>Er is geen logo toegevoegd. Dit kan later met de sponsor worden afgestemd.</p><?php endif; ?></section><section class="detail-card"><h2>E-mailbevestigingen</h2><dl><div><dt>Naar Ton</dt><dd><?= sponsor_admin_mail_badge($app['organizer_state']) ?></dd></div><div><dt>Naar de sponsor</dt><dd><?= sponsor_admin_mail_badge($app['sponsor_state']) ?></dd></div></dl><p class="muted">Een verzendstatus is geen bevestiging dat de ontvanger het bericht heeft gelezen.</p></section></div>
    <?php sponsor_admin_footer();
}
function sponsor_admin_missing(string $csrf): void {
    sponsor_admin_header('Aanvraag niet gevonden', $csrf);
    ?><section class="empty-state"><h1>Aanvraag niet gevonden.</h1><p>Open de aanvraag opnieuw vanuit het overzicht.</p><a href="/beheer/">Terug naar het overzicht</a></section><?php
    sponsor_admin_footer();
}
