// Generate crawlable metadata from the current edition; no browser JavaScript required.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(dist, 'edition.js'), 'utf8'), context, {timeout: 1000});
const config = context.window.IJSBAAN;
const edition = config.editions.find(item => item.id === config.activeEdition);
if (!edition?.place || !edition.start) throw new Error('De actieve editie heeft een plaats en startdatum nodig.');
const base = JSON.parse(fs.readFileSync(path.join(root, 'deploy.json'), 'utf8')).publicUrl;
const brand = 'IJsbaan Neder-Betuwe';
const season = edition.season.replaceAll(' ', '');
const start = new Intl.DateTimeFormat('nl-NL', {day:'numeric', month:'long', year:'numeric', timeZone:'UTC'}).format(new Date(`${edition.start}T12:00:00Z`));
const title = `${brand} | Schaatsen in ${edition.place} ${season}`;
const description = `Schaatsen in ${edition.place} vanaf ${start} bij ${brand}. Bekijk openingstijden, locatie, schaatsmunten en sponsorpakketten voor ${season}.`;
const esc = text => text.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const image = `${base}assets/schaatsplezier.jpg`;
const imageAlt = 'Kinderen met mutsen en handschoenen schaatsen samen op het ijs.';
const schema = {
  '@context': 'https://schema.org',
  '@graph': [
    {'@type':'Organization', '@id':`${base}#organisatie`, name:brand, url:base,
      description:'Een winterse ijsbaan voor kinderen en families in Neder-Betuwe, met wisselende edities in Opheusden en Kesteren.',
      logo:{'@type':'ImageObject',url:`${base}assets/logo-ijsbaan.jpg`,width:1280,height:640},
      email:config.contact.email, telephone:`+31${config.contact.phone.slice(1)}`,
      areaServed:{'@type':'AdministrativeArea',name:'Neder-Betuwe'},
      contactPoint:{'@type':'ContactPoint',name:config.contact.name,contactType:'Sponsoring en organisatie',email:config.contact.email,telephone:`+31${config.contact.phone.slice(1)}`,availableLanguage:'nl'}},
    {'@type':'WebSite','@id':`${base}#website`,url:base,name:brand,alternateName:'IJsbaan Neder Betuwe',inLanguage:'nl-NL',publisher:{'@id':`${base}#organisatie`}},
    {'@type':'WebPage','@id':`${base}#webpagina`,url:base,name:title,description,inLanguage:'nl-NL',isPartOf:{'@id':`${base}#website`},
      about:[{'@id':`${base}#organisatie`},{'@type':'Place',name:`${edition.location}, ${edition.place}`,address:{'@type':'PostalAddress',addressLocality:edition.place,addressCountry:'NL'}}],
      primaryImageOfPage:{'@type':'ImageObject',url:image,width:1100,height:1000,caption:imageAlt}}
  ]
};
const seo = `<!-- SEO:START — generated by scripts/update_seo.mjs -->
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <meta name="robots" content="index, follow, max-image-preview:large">
  <link rel="canonical" href="${base}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="${brand}">
  <meta property="og:locale" content="nl_NL">
  <meta property="og:url" content="${base}">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:image" content="${image}">
  <meta property="og:image:type" content="image/jpeg">
  <meta property="og:image:width" content="1100">
  <meta property="og:image:height" content="1000">
  <meta property="og:image:alt" content="${imageAlt}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(title)}">
  <meta name="twitter:description" content="${esc(description)}">
  <meta name="twitter:image" content="${image}">
  <meta name="twitter:image:alt" content="${imageAlt}">
  <script type="application/ld+json">${JSON.stringify(schema,null,2).replaceAll('<','\\u003c')}</script>
  <!-- SEO:END -->`;
const htmlPath = path.join(dist, 'index.html');
const original = fs.readFileSync(htmlPath, 'utf8');
const marker = /<!-- SEO:START[\s\S]*?<!-- SEO:END -->/;
if (!marker.test(original)) throw new Error('SEO markers ontbreken.');
const html = original.replace(marker, seo);
const photoSources = [...html.matchAll(/<img\b[^>]*src="(assets\/(?:schaatsplezier|samen-op-het-ijs|winter-op-de-baan)[^"]+)"/g)].map(match=>match[1]);
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <url>
    <loc>${base}</loc>
${photoSources.map(src=>`    <image:image><image:loc>${base}${src}</image:loc></image:image>`).join('\n')}
  </url>
</urlset>
`;
const robots = `User-agent: *\nAllow: /\n\nSitemap: ${base}sitemap.xml\n`;
const outputs = [[htmlPath,html],[path.join(dist,'sitemap.xml'),sitemap],[path.join(dist,'robots.txt'),robots]];
const check = process.argv.includes('--check');
for (const [file, expected] of outputs) {
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file,'utf8').replaceAll('\r\n','\n') !== expected.replaceAll('\r\n','\n')) throw new Error(`SEO is verouderd in ${path.basename(file)}. Draai node scripts/update_seo.mjs en commit de wijzigingen.`);
  } else fs.writeFileSync(file,expected);
}
console.log(check ? 'SEO sluit aan op de actieve editie; sitemap en robots.txt kloppen.' : 'SEO, sitemap en robots.txt bijgewerkt.');
